### ISSUE TITLE
Accessibility / Semantics

### ISSUE THREAD

**Issue by UNIcodeX** [caduandrade/davi_flutter#23]
First. Thank you for this wonderful library! 

The issue I'm having is in regards to accessibility. The semantics of some fields are all squished together.

After adding `RendererBinding.instance.setSemanticsEnabled(true)` and running with `flutter run -d chrome --profile --dart-define=FLUTTER_WEB_DEBUG_SHOW_SEMANTICS=true`, this is what I get:

![image](https://user-images.githubusercontent.com/8235002/168680995-57b9ad45-15f9-4c79-9829-6883287c867b.png)

**Comment by caduandrade** [comment]
Hi @UNIcodeX! The image is blurry. But I don't think it's a problem. I'm solving another task and then I see this ok?

**Comment by UNIcodeX** [comment]
Hello. Yes, the image is blurry for the reason that it's a screenshot of live data. The coloration should be enough to see what is happening.

Thank you for taking a look at this issue.
