### ISSUE TITLE
Can't  scroll  to left or right in my android phone? But it can be done in the  android  simulator.

### ISSUE THREAD

**Issue by felixice** [caduandrade/davi_flutter#48]
我不能在安卓手机里面不能向左右滚动？但是在模拟器里面可以。
Can't  scroll  to left or right in my android phone? But it can be done in the  android  simulator.

**Comment by caduandrade** [comment]
Hi @felixice !

I'm aware of that. This package is focused on Web/Desktop but I will try to fix it for mobile.

That happens because there is no drag event for the scroll. Only the small area in the scrollbar. Probably, this area is too small to detect the touch with fingers.

**Comment by caduandrade** [comment]
Fixed by https://github.com/caduandrade/davi_flutter/issues/97
