### ISSUE TITLE
[Flutter 3.3.0+] Scrolling does not work with a trackpad on macOS

### ISSUE THREAD

**Issue by Sesa1988** [caduandrade/davi_flutter#50]
Hi,

after the update to Flutter 3.3.0 the table keeps freezing when multiple entries are in and Im scrolling.
I think they changed internally how scrolling works and maybe thats part of the issue.

I tested it on macOS via trackpad and not sure if this happens as well on Android, iOS, Windows or web.

- Create a table with multiple entries and columns
- Scroll via touchpad

Current behaviour
Table is not scrollable

Expected behaviour
Table will scroll

**Comment by caduandrade** [comment]
Hi @Sesa1988 ! Thanks for the issue.

I just tested it on the web and apparently everything is OK.

Now I have a problem. I don't have macOS to test :cry:. Can I borrow yours? :smile: . I'll see what I can do.

**Comment by Sesa1988** [comment]
> Hi @Sesa1988 ! Thanks for the issue.
> 
> I just tested it on the web and apparently everything is OK.
> 
> Now I have a problem. I don't have macOS to test 😢. Can I borrow yours? 😄 . I'll see what I can do.

I think it has something to do with the bouncing effect that is now default on macOS after upgrading flutter to 3.3.4.
Instead of bouncing it freezes and is not scrollable anymore.

**Comment by Sesa1988** [comment]
I posted a video where I try to scroll all the time in the opposite direction, like really all the time and it does nothing until I did it like 5-10 times :D

**Comment by Sesa1988** [comment]
The example above was actually on the 1.5.1 version. I tested it with the latest version and I can't scroll at all there.
I see the scrollbar, can move it manually with dragging but I can't scroll via trackpad.

I have a footer and the table is above, not sure if this has something to do with this.

```
return Column(
      mainAxisSize: MainAxisSize.max,
      children: [
        Expanded(child: _getTable(context)),
        if (maxCount > pageSize)
          SizedBox(child: _getFooter(context), height: 50),
      ],
    );
```

**Comment by caduandrade** [comment]
Hi @Sesa1988!

As I don't have a mac, would it be possible for you to test a code for me to see if it solves the problem? 
You will need to clone the repo from here and change the `lib/src/internal/table_scrollbar.dart` file.

Find for `ScrollConfiguration` and add the dragDevices:

```
ScrollConfiguration(
                    behavior: ScrollConfiguration.of(context)
                        .copyWith(scrollbars: false,
                        dragDevices: {
                          PointerDeviceKind.touch,
                          PointerDeviceKind.mouse,
                          PointerDeviceKind.invertedStylus,
                          PointerDeviceKind.trackpad
                        }),
```

After this, go to your project and change the `pubspec.yaml` to use an path to the easy_table, example:

```
  easy_table: 
    path: /cadu/easy_table_flutter
```

**Comment by Sesa1988** [comment]
Hi @caduandrade 

That's no problem, I'll test it in the next few days or next week.

**Comment by Sesa1988** [comment]
> Hi @Sesa1988!
> 
> As I don't have a mac, would it be possible for you to test a code for me to see if it solves the problem? You will need to clone the repo from here and change the `lib/src/internal/table_scrollbar.dart` file.
> 
> Find for `ScrollConfiguration` and add the dragDevices:
> 
> ```
> ScrollConfiguration(
>                     behavior: ScrollConfiguration.of(context)
>                         .copyWith(scrollbars: false,
>                         dragDevices: {
>                           PointerDeviceKind.touch,
>                           PointerDeviceKind.mouse,
>                           PointerDeviceKind.invertedStylus,
>                           PointerDeviceKind.trackpad
>                         }),
> ```
> 
> After this, go to your project and change the `pubspec.yaml` to use an path to your the easy_table, example:
> 
> ```
>   easy_table: 
>     path: /cadu/easy_table_flutter
> ```

Hi @caduandrade 

I tested it and it does not fix the issue but I also tested your example application and the same issue is present there.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "example debug",
            "cwd": "example",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug",
            "args": [
                "-d",
                "macos",
            ]
        },
    ]
}
```
Could you open a bug on the flutter repository with your example application, thats pretty good for reproduction.

**Comment by caduandrade** [comment]
Hi @Sesa1988 ! 

Could you make one more attempt? Just checkout the `bugfix/50-scrolling-trackpad` branch and test.

**Comment by Sesa1988** [comment]
> Hi @Sesa1988 !
> 
> Could you make one more attempt? Just checkout the `bugfix/50-scrolling-trackpad` branch and test.

It sadly does not work as well.

**Comment by Sesa1988** [comment]
> Hi @Sesa1988 !
> 
> Could you make one more attempt? Just checkout the `bugfix/50-scrolling-trackpad` branch and test.

Im not sure this could be related. https://github.com/flutter/flutter/issues/114889

**Comment by caduandrade** [comment]
I think so. :-(

**Comment by Sesa1988** [comment]
> I think so. :-(

I opened a bug and someone mentioned this solution. I tested it and this works but Im not sure if this is enough for your feature set but maybe it's enough for a right direction.

```
onPointerPanZoomUpdate: (e) {
          if (e.panDelta.dy != 0) {
            _scrollControllers.vertical.position.pointerScroll(-e.panDelta.dy);
          }
        },
```

**Comment by caduandrade** [comment]
Hi @Sesa1988 ! If it's working for you, that's ok. Is it possible for you to make a merge request? But attention because I did a merge today. Please update your code first.

**Comment by Sesa1988** [comment]
> Hi @Sesa1988 ! If it's working for you, that's ok. Is it possible for you to make a merge request? But attention because I did a merge today. Please update your code first.

I think it would be easier for you to update. Im not sure if this solution is valid and just really just this part, I pasted it in and it worked.

In your fix branch you added this already just with another implementation.

**Comment by caduandrade** [comment]
@Sesa1988 , you made this change in `_EasyTableState` of `table.dart` right?

**Comment by Sesa1988** [comment]
> @Sesa1988 , you made this change in `_EasyTableState` of `table.dart` right?

Yes :)

**Comment by caduandrade** [comment]
@Sesa1988 ,

I made a commit to the main branch. You can test it? On web and linux desktop this event is not fired. I have no way to test. I just thought it was weird to use a negative value as if on macOS it was inverted...

If it's ok for you, I'll publish it as a patch.

**Comment by Sesa1988** [comment]
> @Sesa1988 ,
> 
> I made a commit to the `main` branch. Can you test it? On web and linux desktop this event is not fired. I have no way to test. I just thought it was weird to use a negative value as if on macOS it was inverted...
> 
> If it's ok for you, I'll publish it as a patch.

Yea thats weird but even the scroll-settings on macOS are weird so who knows :D 

I will test it now.

**Comment by caduandrade** [comment]
@Sesa1988 , version `2.1.0` released! Thank you for your help!

**Comment by Sesa1988** [comment]
> @Sesa1988 , version `2.1.0` released! Thank you for your help!

I busted noticed that there is no velocity, its like jumping and stops instantly but that could be another issue :D
