### ISSUE TITLE
Ability to delegate sorting logic outside of table

### ISSUE THREAD

**Issue by ykrasik** [caduandrade/davi_flutter#58]
Hi @caduandrade :)

Sorry for the amount of requests, but I have another one, please!

It'd be great to be able to delegate the sorting logic outside of the table. I'd like to use the table header's ability to select & display how the table is sorted, but let another system handle the actual sorting. There are at least 2 use cases for this:
1. Keyboard navigation - Adding keyboard navigation that has non-trivial behavior (jump 3 down and 1 right, like a chess knight 🤷) requires the code that runs that logic to know exactly what the user sees. This is easier to do by keeping the source of truth of the table state outside the table, in a store that can handle that custom logic.
2. The table is lazily populated (infinite scroll / paging) from some web API which supports sorting, in which case the sorting logic is delegated to the API.

Probably this would be an `onSort` callback that receives a list of tuples of `[columnName, sortDirection]`

Hope to hear your thoughts on the matter!

**Comment by caduandrade** [comment]
more request = better package :wink:

**Comment by caduandrade** [comment]
I will finish the #61 issue first ok?

I have plans to have table and grid views. "Data view" will be more generic.

**Comment by ykrasik** [comment]
Of course, it's your vision of the package ☺️
You're very responsive on these requests, so thanks a lot for that!

**Comment by caduandrade** [comment]
#61 done. Now it's `https://pub.dev/packages/davi`

**Comment by caduandrade** [comment]
Hi @ykrasik ! Back to this issue...

We have to sort the internal row list (`list.sort`). The Flutter sort method receives `int compare(E a, E b)`.

I thought of this typedef: 

`typedef DaviColumnCustomSort<DATA> = int Function(DATA a, DATA b, List<DaviColumn<DATA>> sortedColumns)`

As the table accepts multiple sorts, it receives a list of sorted columns. With the `DaviColumn`, you can get the enum `TableSortOrder` (`column.order`) or the default sort method (`column.sort`).

The model is responsible for sorting. It could have the attribute:

`DaviColumnCustomSort<DATA>? customSort` (or another name)

Example:

```dart
  @override
  void initState() {
    super.initState();

    List<Person> rows = [];

    Random random = Random();
    for (int i = 1; i < 500; i++) {
      rows.add(Person('User $i', random.nextInt(100)));
    }

    _model = DaviModel<Person>(
        rows: rows,
        columns: [
          DaviColumn(name: 'Name', stringValue: (row) => row.name),
          DaviColumn(name: 'Value', intValue: (row) => row.value)
        ],
        customSort: _myCustomSort);
  }

  /// same default behavior (compound sort)
  int _myCustomSort(
      Person a, Person b, List<DaviColumn<Person>> sortedColumns) {
    int r = 0;
    for (int i = 0; i < sortedColumns.length; i++) {
      final DaviColumnSort<Person> sort = sortedColumns[i].sort!;
      final TableSortOrder order = sortedColumns[i].order!;

      if (order == TableSortOrder.descending) {
        r = sort(b, a);
      } else {
        r = sort(a, b);
      }
      if (r != 0) {
        break;
      }
    }
    return r;
  }
```

Currently, if no columns are sorted, the sort method is not called and maintains the natural order of data added to the model.

Will it work right?

**Comment by caduandrade** [comment]
Hi @ykrasik ! Back to this issue...

Tell me if I understand correctly.

You would like to be notified (listener) by sort clicks to repopulate the table. At this point, you will call the WEB API using the sorted columns to retrieve the data in the correct order. Even if the header has sorting enabled, the data must always be presented in the natural order in which it was added.

In this case, in addition to `onSort`, you will need to allow sort clicks, but not use the column's sort algorithm. I believe that it will not help to create the column with `sort: (a, b) => 0`. This will also modify the natural order.

Perhaps some attribute in the model to inform that the ordering will be done externally, just to allow the clicks on the header and the `onSort` notification.

`bool externalSort`?

**Comment by ykrasik** [comment]
Hi @caduandrade,

Yes, that's pretty much it. `bool externalSort` & `onSort` listener sounds good. I suppose you could also offer it as a single `externalSort` listener, the presence of which acts as both `bool externalSort` & `onSort`. Any one of these approaches would solve the issue.

**Comment by caduandrade** [comment]
Great. I will keep both. Maybe the onSort can be used to show some warning on screen or something else.

**Comment by caduandrade** [comment]
Hi @ykrasik!

I made an example of simulating sorting on the server side while loading the data.

I believe that's it. If you need anything else, let me know. Soon I will publish the new version.

```dart
class Person {
  Person(this.name, this.age);

  final String name;
  final int age;
}

class MainWidget extends StatefulWidget {
  const MainWidget({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => MainWidgetState();
}

enum ColumnId { name, age }

class MainWidgetState extends State<MainWidget> {
  late DaviModel<Person> _model;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _model = DaviModel<Person>(columns: [
      DaviColumn(
          id: ColumnId.name, name: 'Name', stringValue: (row) => row.name),
      DaviColumn(id: ColumnId.age, name: 'Age', intValue: (row) => row.age)
    ], onSort: _onSort, ignoreSort: true);
    loadData();
  }

  void loadData([DaviColumn<Person>? column]) {
    Future<List<Person>>.delayed(const Duration(seconds: 1), () {
      List<Person> rows = [
        Person('Linda', 33),
        Person('Pamela', 22),
        Person('Steven', 21),
        Person('James', 37),
        Person('Amanda', 43),
        Person('Cadu', 35)
      ];
      if (column != null) {
        final TableSortOrder order = column.order!;
        rows.sort((a, b) {
          switch (column.id) {
            case ColumnId.name:
              return order == TableSortOrder.ascending
                  ? a.name.compareTo(b.name)
                  : b.name.compareTo(a.name);
            case ColumnId.age:
              return order == TableSortOrder.ascending
                  ? a.age.compareTo(b.age)
                  : b.age.compareTo(a.age);
          }
          return 0;
        });
      }
      return rows;
    }).then((list) {
      setState(() {
        _loading = false;
        _model.replaceRows(list);
      });
    });
  }

  void _onSort(List<DaviColumn<Person>> sortedColumns) {
    setState(() {
      _loading = true;
      _model.removeRows();
    });
    final DaviColumn<Person>? column =
        sortedColumns.isNotEmpty ? sortedColumns.first : null;
    loadData(column);
  }

  @override
  Widget build(BuildContext context) {
    return Davi(_model,
        tapToSortEnabled: !_loading,
        lastRowWidget:
            _loading ? const Center(child: Text('Loading...')) : null);
  }
}
```

**Comment by ykrasik** [comment]
Great, will test ASAP, thanks for the quick work!

**Comment by ykrasik** [comment]
Ran across a new issue while implementing this: #66
