### ISSUE TITLE
Keeping model in state doesn't work with conditional rendering

### ISSUE THREAD

**Issue by ykrasik** [caduandrade/davi_flutter#66]
Hi @caduandrade :)

It seems like the recommended approach of keeping the model in the widget state doesn't work in case of conditional rendering, meaning when the Davi isn't rendered at all due to a condition preventing it. For example, if a custom loader is rendered while data is loaded.
See the below example code, which is based on the "external sort" template code, but it renders a different widget instead of the Davi table when it is loading.

```dart
import 'dart:ui';

import 'package:davi/davi.dart';
import 'package:flutter/material.dart';

void main() {
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    print("Unhandled Flutter error: ${details.exception} ${details.stack}");
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    print("Unhandled Flutter Platform error: $error $stack");
    return true;
  };

  runApp(const MainWidget());
}

class MainWidget extends StatefulWidget {
  const MainWidget({super.key});

  @override
  State createState() => MainWidgetState();
}

class Person {
  Person(this.name, this.age);

  final String name;
  final int age;
}

enum ColumnId { name, age }

class MainWidgetState extends State<MainWidget> {
  late DaviModel<Person> _model;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _model = DaviModel<Person>(columns: [
      DaviColumn(id: ColumnId.name, name: 'Name', stringValue: (row) => row.name),
      DaviColumn(id: ColumnId.age, name: 'Age', intValue: (row) => row.age)
    ], onSort: _onSort, ignoreSort: true);
    loadData();
  }

  void loadData([DaviColumn<Person>? column]) {
    Future<List<Person>>.delayed(const Duration(seconds: 1), () {
      List<Person> rows = [
        Person('Linda', 33),
        Person('Pamela', 22),
        Person('Steven', 21),
        Person('James', 37),
        Person('Amanda', 43),
        Person('Cadu', 35)
      ];
      if (column != null) {
        final TableSortOrder order = column.order!;
        rows.sort((a, b) {
          switch (column.id) {
            case ColumnId.name:
              return order == TableSortOrder.ascending
                  ? a.name.compareTo(b.name)
                  : b.name.compareTo(a.name);
            case ColumnId.age:
              return order == TableSortOrder.ascending
                  ? a.age.compareTo(b.age)
                  : b.age.compareTo(a.age);
          }
          return 0;
        });
      }
      return rows;
    }).then((list) {
      setState(() {
        _loading = false;
        _model.replaceRows(list);
      });
    });
  }

  void _onSort(List<DaviColumn<Person>> sortedColumns) {
    setState(() {
      _loading = true;
      _model.removeRows();
    });
    final DaviColumn<Person>? column = sortedColumns.isNotEmpty ? sortedColumns.first : null;
    loadData(column);
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const MaterialApp(
          home: Scaffold(
        body: Center(child: Text('Loading...')),
      ));
    } else {
      return MaterialApp(
          home: Scaffold(
        body: Davi(_model,
            tapToSortEnabled: !_loading,
            lastRowWidget: _loading ? const Center(child: Text('Loading...')) : null),
      ));
    }
  }
}
```

The above renders fine the first time, but if you click on any of the headers, which will set `_loading=true` and unmount the Davi, you will then get the following exception:

```
Once you have called dispose() on a DaviModel<Person>, it can no longer be used. 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:147:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:154:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:330:27)
#3      DaviModel._updateRows (package:davi/src/model.dart:275:7)
#4      DaviModel.replaceRows (package:davi/src/model.dart:104:5)
#5      MainWidgetState.loadData.<anonymous closure>.<anonymous closure> (package:qfiler/test4.dart:79:16)
#6      State.setState (package:flutter/src/widgets/framework.dart:1114:30)
#7      MainWidgetState.loadData.<anonymous closure> (package:qfiler/test4.dart:77:7)
```

I ran into this issue previously as well, but up until the "external sort" feature I was able to work around it by re-creating the model on each `build` call. The "external sort" feature doesn't work if the model is recreated on each render (seems like the model keeps `_sortedColumns` as state which is lost if the model is recreated), so I had to move the model to the widget's state.

I tried the `lastRowWidget` approach, but it only allows the loader to be rendered as the last row, whereas what I want to achieve is a full screen loader that will be rendered instead of the table, or have the table expand to take up all the available space but allow me to render a custom widget inside that space. To be fully accurate - I want to render the table header and have a custom loader take up the rest of the available space on screen.
What I've been doing so far for loading is rendering a Column with an empty Davi so it displays the table header, and below it as a ListView a bunch of skeleton shimmering rows with the height manually set to the height of Davi rows (See screenshot below). So if Davi supported this natively, that'd be nice. But I'd also want to be able to display a centered full-screen error state in case of error, so the overall most flexible solution would be to allow the model to be re-used somehow after being disposed. If that doesn't make sense, what other options do I have to achieve what I'm trying?

![image](https://user-images.githubusercontent.com/5993890/214039534-01f73486-68fa-4a93-b84d-49d4098fb17c.png)

**Comment by ykrasik** [comment]
I suppose the root cause is that disposing of `Davi` also disposes of the model: https://github.com/caduandrade/davi_flutter/blob/main/lib/src/davi.dart#L108

Maybe this shouldn't happen if the model is managed outside of the Davi?

**Comment by caduandrade** [comment]
The model disposal in the Widget is very weird. Does not make sense. I'll take a look at it.

**Comment by caduandrade** [comment]
It shouldn't be a `dispose` (of course), it should just remove the listener. Fixing...
Thanks for pointing out the problem. It was accurate.

**Comment by caduandrade** [comment]
I noticed that `Davi` is changing the scroll offset to zero if it receives a new instance of the model. Maybe it should keep the same offset as well. Any other problems just let me know.
Thanks for reporting the bug.

**Comment by ykrasik** [comment]
Thanks for doing a great job on handling these :)

**Comment by ykrasik** [comment]
Works well now 🥇
