### ISSUE TITLE
Make it easier to have sort state managed outside of DaviModel

### ISSUE THREAD

**Issue by ykrasik** [caduandrade/davi_flutter#68]
Hi @caduandrade :)

I'm trying to move the "columns sorted by" source of truth outside of the table, into my own data store. I mean the column names & directions of the sort.
This can be used, for example, to persist the sort preferences of the user into disk and restore them when the app is re-opened.

The flow looks roughly like this:
1. User clicks a header, table updates its `_sortedColumns` and calls `onSort`.
2. `onSort` listener updates the data store with the current sort.
3. Data store runs a reaction (I'm using MobX but it doesn't matter) which sets the sort of the model according to the data store's sort state. Basically, it calls [model.sort](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/model.dart#L197) with an equal value to what it just received from `onSort`. 

Structuring it like this makes it possible to programatically control the sort state in places that don't have access to the DaviModel - I only need to deal with the store (which in my case is shared between multiple widgets, unlike the model) and setting the sort state on the store will get it applied to the DaviModel by a reaction. Also, there is no special handling needed for restoring the sort state from disk - the store is initialized with state restored from disk and that's it.

There is another use case for giving the store responsibility over the sort state - it allows the store to validate or change the sort requested by the user. Maybe a combination of columns is not supported for sorting. Or maybe the store would like to disallow setting a "no sort" state (Opened a separate issue about this at #67)

There are some rough edges with this approach currently:
* The API for setting the sort state ([model.sort](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/model.dart#L197)) and the API for getting the sort state ([model.sortedColumns](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/model.dart#L37)) deals with different objects. [ColumnSort](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/column_sort.dart) deals with column indices, but [DaviColumn](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/column.dart#L21) itself does not have an `index` property, which makes the mapping between the two implicit. Also, if columns can be re-arranged (in the future? :) ) this will become brittle. I think it would've been more convenient to rely on column `name` when defining ColumnSort, though it is optional, so not sure what the best approach would be.
* [ColumnSort](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/column_sort.dart) has no value semantics, meaning it cannot has no `==` by value. This comes into play in the next point.
* [model.sort](https://github.com/caduandrade/davi_flutter/blob/main/lib/src/model.dart#L197) always performs its actions and calls the `onSort` observer, even if setting the sort to the already existing sort. This can create an endless loop in the flow I described above, which I had to stop by running conditional updates.

These are my observations. Maybe they can be improved, maybe not :)

**Comment by caduandrade** [comment]
Hi @ykrasik!

I think all suggestions for this issue were already made in #67 right?

**Comment by ykrasik** [comment]
Yup, thanks for the great work!
