### ISSUE TITLE
How to get a reference to an assigned widget with cellBuilder?

### ISSUE THREAD

**Issue by valientegaston** [caduandrade/davi_flutter#72]
This is an example for a custom Widget in a cell.. 

_model = DaviModel<Person>(rows: rows, columns: [
      DaviColumn(name: 'Name', stringValue: (row) => row.name),
      DaviColumn(
          name: 'Rate',
          width: 150,
          cellBuilder: (context, row) => StarsWidget(stars: row.data.stars))
    ]);

How could I get a reference to StartsWidget?
e.g. 

Widget s = _model.getColumn(id).cellBuilder;

Thank you

**Comment by caduandrade** [comment]
Hi @valientegaston!

You are unable to get the reference to the `Widget`. It's just a builder. I don't know exactly why you want this but it's not the correct Flutter style because the `Widget` will be created at each rebuild ok? You shouldn't keep a reference to any `Widget` but to models and/or controllers.

In this case, I believe you should be concerned with the model (data). Example: 

`_model.rowAt(2).stars`

Or if you need to directly change the Widget without rebuilding the grid (good), it should be through a controller or `ChangeNotifier`.

**Comment by valientegaston** [comment]
That last thing you say is exactly what I want to do. Can you give me a small example? Thank you.

**Comment by caduandrade** [comment]
Hi @valientegaston .

There is more than one way to implement this.
There are packages like Provider and BLOC. Flutter also provides mechanisms for communicating between widgets.
This is a simple way (pure Flutter) to notify only one sheet.

I don't particularly like the name `AnimatedBuilder` as it's not just for animation. It can listen to any `Listenable` (`ChangeNotifier`)

```dart
import 'dart:math';

import 'package:davi/davi.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const ExampleApp());
}

class Person extends ChangeNotifier {
  Person(this.name, this.age);

  final String name;
  final int age;

  int _value = 1;

  int get value => _value;

  set value(int value) {
    if (_value != value) {
      _value = value;
      notifyListeners();
    }
  }
}

class ExampleApp extends StatelessWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Davi Example',
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  DaviModel<Person>? _model;

  @override
  void initState() {
    super.initState();

    List<Person> rows = [];

    Random random = Random();
    for (int i = 1; i < 500; i++) {
      rows.add(Person('User $i', 20 + random.nextInt(50)));
    }
    rows.shuffle();

    _model = DaviModel<Person>(rows: rows, columns: [
      DaviColumn(name: 'Name', stringValue: (data) => data.name),
      DaviColumn(name: 'Age', intValue: (data) => data.age),
      DaviColumn(
          name: 'Value',
          cellBuilder: (context, row) => AnimatedBuilder(
              animation: row.data,
              builder: (BuildContext context, Widget? child) =>
                  Text('${row.data.value}'))),
    ]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(children: [
      Center(
          child: ElevatedButton(
              onPressed: () => _model!.rowAt(1).value++,
              child: const Text('Inc row 1'))),
      Expanded(child: Davi<Person>(_model))
    ], crossAxisAlignment: CrossAxisAlignment.stretch));
  }
}
```
