### ISSUE TITLE
Adding .copyWith() method to DaviThemeData

### ISSUE THREAD

**Issue by animator** [caduandrade/davi_flutter#73]
Hi @caduandrade,

Thanks for creating this wonderful project.

Currently, there is no `copyWith()`  method for `DaviThemeData` class provided in the source below.
https://github.com/caduandrade/davi_flutter/blob/main/lib/src/theme/theme_data.dart

Can you please add this method so that it is easier to use themes with slight modifications across different tables.

Thanks!

**Comment by caduandrade** [comment]
Hi @animator! Sorry for the delay. I am very busy. It's done. :+1:
