### ISSUE TITLE
Project showcase note

### ISSUE THREAD

**Issue by animator** [caduandrade/davi_flutter#75]
Hey @caduandrade,

Don't know if you are aware. But, we are building an awesome API tool using Flutter and we use davi and multi_split_view.

Link - https://github.com/foss42/api-dash

Just wanted to check if you have any section where you feature production apps that use your package(s).

Thanks!

**Comment by caduandrade** [comment]
Hi @animator !

How fantastic. I loved. Congratulations! I'm glad to know that my packages are useful. I already marked a star on Github :wink: 

Of course, I can create that session.

I'm wanting to move the documentation somewhere else like Hashnode or Docusaurus. I think it's really bad that you need to publish a new package version just to update the documentation in pub.dev.

**Comment by animator** [comment]
Great to hear that you liked the project @caduandrade  :)
Sure. Please feel free to add APi Dash whenever you publish a new documentation site. No worries.
Just wanted to let you know that I evaluated a lot of packages and ultimately loved the ability to customize davi.
It's insane. I had already starred the project ⭐️
Thank you for building it! 🙏
