### ISSUE TITLE
on screen keyboard does not show

### ISSUE THREAD

**Issue by kevin-haynie** [caduandrade/davi_flutter#77]
It seems that the on screen keyboard is not triggered for editable cells when running on Windows laptop mode.  This is a big problem for me since Windows laptop mode is my primary target and I have lots of editable fields.  

Is this something you have seen before and are there any workarounds?

Thanks in advance...

**Comment by caduandrade** [comment]
Hi @kevin-haynie ! I don't know what could be related to Davi. Maybe the Focus widget. The problem is that I don't have a Windows to test, only Linux, web and Android :-(

**Comment by kevin-haynie** [comment]
OK, thanks for your response.  I will do a little more digging to see if I can find the source of the problem.  If I find it, I will let you know.  

I agree with you that focus is probably one of the reasons why this isn't working properly.

**Comment by kevin-haynie** [comment]
OK, I found the problem.

In cell_widget.dart, you used the Semantics widget at the bottom of your build method. That's fine except for editable fields. In the case things are editable, you cannot include the readonly: true parameter. Doing so tells Windows that the field is not editable and therefore no on screeen keyboard is necessary.

I recommend adding a new parameter to DaviColumn() called 'editable' which is a bool that can drive whether or not you include readonly: true in your Semantics widget.

I tested removing readonly true from your semantics widget and the on screen keyboard pops every time.

**Comment by caduandrade** [comment]
Hi @kevin-haynie !

Is it possible to be null? If so, I think it would be better because just setting an attribute as editable will not make the cell actually editable without instantiating a Widget itself.
I think it would be better, if necessary, to expose these semantics `readOnly` later instead of an `editable` attribute. What do you think?

**Comment by kevin-haynie** [comment]
Sure however you want to do it. You could include a parameter called
readOnly which defaults to true. Then I would set it to false for my
editable columns.

**Comment by caduandrade** [comment]
@kevin-haynie, done. Version 3.4.0. You won't need to change anything. If you need anything, let me know.
