### ISSUE TITLE
Enable the scroll horizontal and vertical for android devices

### ISSUE THREAD

**Issue by starklord** [caduandrade/davi_flutter#82]
Hi, this is a great product, its very simple and neat. I dont know why the scroll doesnt work on android devices and maybe on ios devices.
Can you please enable this or fix it. Or maybe can you suggest me some trick to do because my project is now reaching the mobile world and i want to keep using this amazing table.

**Comment by caduandrade** [comment]
Fixed by https://github.com/caduandrade/davi_flutter/issues/97
