### ISSUE TITLE
Column Summary (Footer)

### ISSUE THREAD

**Issue by kitesoft** [caduandrade/davi_flutter#83]
Hi, Summary columns are used to represent calculations of specific data from a dataTable.
For example, the "Invoices" table displays the total amount for all invoice items stored in the "Items" table.

As a result, the Total summary column, calculating the total items amount 

[https://www.teamdesk.net/help/img/image-93.png](https://www.teamdesk.net/help/img/image-93.png)

**Comment by caduandrade** [comment]
Hi @kitesoft! 

There is currently no footer. You can get a little closer by using custom cell sorting. In any case, it wouldn't be left out of the scroll. Depending on the case, it won't work. :disappointed: 
The footer is in the TODO list.
