### ISSUE TITLE
programmatically jump/scroll to a specific row

### ISSUE THREAD

**Issue by Haugpro** [caduandrade/davi_flutter#94]
is there a way to jump or scroll to a specific row programmatically?
This is a must have feature for a planned desktop app. Comparing some datagrids for flutter, davi fits best by now, except of this feature.
Maybe I have not seen it

**Comment by caduandrade** [comment]
Hi @Haugpro !

I'm traveling on vacation, when I get back I'll see this better but I believe you can pass your own ScrollController and use it then you should be able to use jump normally. Isn't this the case reported in #93?

**Comment by Haugpro** [comment]
thanks for this quick answer. Did not want to disturb you on your vacation. You are right, it's the same question as #93, did not look close enough. I'm not sure I have enough flutter experience to replace/overwrite the scroll controller, but I will try
